# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41fd88e036868ae45cb71d618ce8e2db75c480b96fe746a06a040f2f2938ca4135471afec9d69dc73e08eabd4c94f2945b051139e02629244765199301f6c057

test:
  secret_key_base: 82262795f731fb4ffecea5db584c03ebaf4924b41ddf57fded6365db966a1b652f1a012200fe2c99f30625c5ae26ad6f44f00a9ebbaa42463d70c6e7af543589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
